project:
  type: website

website:
  title: "Kaan Öztürk"
  twitter-card: true
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        menu: 
          - text: All posts
            href: blog.qmd
          - text: English
            href: blog-en.qmd
          - text: Türkçe
            href: blog-tr.qmd
format:
  html:
    theme: flatly 
    css: styles.css



